version: '3'

services:
  api:
    build:
      context: ./backend
      dockerfile: api.Dockerfile
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./backend:/usr/src/app

  database:
    build:
      context: ./database
      dockerfile: database.Dockerfile
    ports:
      - "3306:3306"
    restart: always
